services:
  # ejabberd-grpc-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5051:5051"
  #     - "5222:5222"
  envoy-proxy:
    image: envoyproxy/envoy:v1.25-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports: 
    - "8081:8081"
    depends_on: 
      - ej
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]

  ej:
    image: ejabberd