services:
  ejabberd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5051:5051"
      - "5222:5222"

  envoy-proxy:
    image: envoyproxy/envoy:v1.25-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports: 
    - "8081:8081"
    depends_on: 
      - ej
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]

  ej:
    image: ejabberd
    depends_on:
      - db
    restart: always
    links:
      - db
  
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ejabberd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ejabberd"]
      interval: 10s
      retries: 5
    ports: 
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: 
